import {
  colors,
  spacing,
  radii,
  typeSizes,
  motion,
  layout,
} from "../src/tokens";

/** CSS OKLCH to sRGB, clamped to the device gamut. Native cannot parse OKLCH. */
export function nativeColor(value: string): string {
  const match = /^oklch\(([\d.]+)% ([\d.]+) ([\d.]+)(?: \/ ([\d.]+))?\)$/.exec(
    value,
  );
  if (!match) throw new Error(`Unsupported token colour: ${value}`);
  const l = Number(match[1]) / 100,
    c = Number(match[2]),
    h = (Number(match[3]) * Math.PI) / 180;
  const a = c * Math.cos(h),
    b = c * Math.sin(h);
  const ll = (l + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const mm = (l - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const ss = (l - 0.0894841775 * a - 1.291485548 * b) ** 3;
  const channel = (v: number) =>
    Math.round(
      Math.max(
        0,
        Math.min(
          1,
          v <= 0.0031308 ? 12.92 * v : 1.055 * v ** (1 / 2.4) - 0.055,
        ),
      ) * 255,
    );
  const rgb = [
    channel(4.0767416621 * ll - 3.3077115913 * mm + 0.2309699292 * ss),
    channel(-1.2684380046 * ll + 2.6097574011 * mm - 0.3413193965 * ss),
    channel(-0.0041960863 * ll - 0.7034186147 * mm + 1.707614701 * ss),
  ];
  return match[4]
    ? `rgba(${rgb.join(", ")}, ${match[4]})`
    : `#${rgb.map((v) => v.toString(16).padStart(2, "0")).join("")}`;
}
export function nativeThemeSource() {
  const theme = {
    colors: Object.fromEntries(
      Object.entries(colors).map(([key, value]) => [key, nativeColor(value)]),
    ),
    spacing,
    radii,
    typeSizes,
    motion,
    layout,
  };
  return `/* Generated by packages/core/scripts/tokens.ts. Do not edit. */\nexport const theme = ${JSON.stringify(theme, null, 2)} as const;\n`;
}
