export const plannerCopy = {
  emptyDay: "Nothing planned.",
  firstDay: "Nothing planned yet.",
  emptyList: "Nothing planned for today.",
  emptyWeek: "Nothing planned this week.",
  anytime: "Tasks for today without a time wait here.",
  undated: "Tasks without a day land here until you schedule them.",
  noGoals: "No goals yet",
  goalExplanation: "A goal shows where you are and where you should be today. Link tasks to it, track a number, or tick off milestones.",
  firstTaskTitle: "Your day starts here.",
  firstTaskExplanation: "Type a task the way you would say it. Give it a time and it lands on this timeline.",
  dragHint: "Drag a task from the tray onto the timeline to give it a time.",
  phoneDragHint: "Hold a task and drag it onto the timeline to give it a time.",
  touchHint: "Tap a task to give it a time.",
  examples: ["lunch with Priya 1pm", "gym tomorrow 7am", "essay fri 5pm 2h"],
} as const;
