import type { QuickAddResult } from "./quickAdd";
export const quickAddCases: { text: string; expected: Partial<QuickAddResult> }[] = [
    { text: "gym tomorrow 7am", expected: { title: "Gym", date: "2026-09-30", time: "07:00" } },
    { text: "practice piano tomorrow #music", expected: { title: "Practice piano", areaId: "music", date: "2026-09-30" } },
    { text: "call amma", expected: { title: "Call amma" } },
    { text: "essay fri #econ 2h", expected: { title: "Essay", areaId: "school", projectId: "econ", date: "2026-10-02", durationMinutes: 120 } },
    { text: "read for 20 minutes at 9", expected: { title: "Read for 20 minutes", time: "09:00" } },
    { text: "standup 9:30 15m #biz", expected: { title: "Standup", areaId: "biz", time: "09:30", durationMinutes: 15 } },
    { text: "revise 1h30m tonight", expected: { title: "Revise", date: "2026-09-29", durationMinutes: 90 } },
    { text: "buy milk later", expected: { title: "Buy milk", date: null } },
    { text: "lunch at 1", expected: { title: "Lunch", time: "13:00" } },
    { text: "report tue", expected: { title: "Report", date: "2026-10-06" } },
    { text: "", expected: { title: "" } },
    { text: " \t\n ", expected: { title: "" } },
    { text: "study on Wednesday 1.5hrs", expected: { title: "Study", date: "2026-09-30", durationMinutes: 90 } },
    { text: "call at 12am", expected: { title: "Call", time: "00:00" } },
    { text: "lunch 12pm", expected: { title: "Lunch", time: "12:00" } },
    { text: "read #unknown", expected: { title: "Read #unknown" } },
    { text: "essay #ECON101", expected: { title: "Essay", projectId: "econ", areaId: "school" } },
    { text: "standup #business", expected: { title: "Standup", areaId: "biz" } },
    { text: "call today fri", expected: { title: "Call fri", date: "2026-09-29" } },
    { text: "standup every weekday 9:30", expected: { title: "Standup", date: "2026-10-01", time: "09:30", repeat: { every: 1, unit: "week", weekdays: [1, 2, 3, 4, 5] } } },
    { text: "gym every 2 weeks on mon wed", expected: { title: "Gym", date: "2026-10-05", repeat: { every: 2, unit: "week", weekdays: [1, 3] } } },
    { text: "club every month on the last friday", expected: { title: "Club", date: "2026-10-30", repeat: { every: 1, unit: "month", monthDay: { kind: "weekday", nth: -1, weekday: 5 } } } },
    { text: "pay rent every month on the 15th", expected: { title: "Pay rent", date: "2026-10-15", repeat: { every: 1, unit: "month", monthDay: { kind: "day", day: 15 } } } },
    { text: "water plants every 3 days after done", expected: { title: "Water plants", repeat: { every: 3, unit: "day", basis: "completion" } } },
    { text: "piano daily until 18 dec", expected: { title: "Piano", repeat: { every: 1, unit: "day", ends: { kind: "on", date: "2026-12-18" } } } },
    { text: "physio weekly 10 times", expected: { title: "Physio", repeat: { every: 1, unit: "week", ends: { kind: "after", count: 10 } } } },
    { text: "call mom fri 5pm remind 30m before", expected: { title: "Call mom", date: "2026-10-02", time: "17:00", reminders: [{ type: "before", minutes: 30 }] } },
    { text: "essay due fri remind 2 days before due at 6pm", expected: { title: "Essay", deadline: "2026-10-02", reminders: [{ type: "deadline", daysBefore: 2, time: "18:00" }] } },
    { text: "lab report due 9 oct", expected: { title: "Lab report", deadline: "2026-10-09" } },
  ];
