import type { QuickAddResult } from "./quickAdd";
/** One source for the public token table and executable parser examples. */
export const quickAddGrammar: { tokens: string[]; meaning: string; suffix: string; expected: Partial<QuickAddResult> }[] = [
  { tokens: ["today", "tonight"], meaning: "The local day supplied by the client", suffix: "", expected: { date: "2026-09-29" } },
  { tokens: ["tomorrow", "tmr", "tmrw", "tom"], meaning: "The next local day", suffix: "", expected: { date: "2026-09-30" } },
  { tokens: ["later", "someday"], meaning: "No date", suffix: "", expected: { date: null } },
  { tokens: ["mon", "monday"], meaning: "Next Monday, even if today is Monday", suffix: "", expected: { date: "2026-10-05" } },
  { tokens: ["tue", "tues", "tuesday"], meaning: "Next Tuesday", suffix: "", expected: { date: "2026-10-06" } },
  { tokens: ["wed", "wednesday", "on Wednesday"], meaning: "Next Wednesday; on is optional", suffix: "", expected: { date: "2026-09-30" } },
  { tokens: ["thu", "thur", "thurs", "thursday"], meaning: "Next Thursday", suffix: "", expected: { date: "2026-10-01" } },
  { tokens: ["fri", "friday"], meaning: "Next Friday", suffix: "", expected: { date: "2026-10-02" } },
  { tokens: ["sat", "saturday"], meaning: "Next Saturday", suffix: "", expected: { date: "2026-10-03" } },
  { tokens: ["sun", "sunday"], meaning: "Next Sunday", suffix: "", expected: { date: "2026-10-04" } },
  { tokens: ["7am", "7:00am", "at 7 am"], meaning: "12-hour time, with optional at and spaces", suffix: "", expected: { time: "07:00" } },
  { tokens: ["5pm", "5:00pm", "at 5 pm"], meaning: "12-hour afternoon time", suffix: "", expected: { time: "17:00" } },
  { tokens: ["17:30", "at 17:30"], meaning: "24-hour time", suffix: "", expected: { time: "17:30" } },
  { tokens: ["at 1"], meaning: "Bare hour with at; hours below 7 mean afternoon", suffix: "", expected: { time: "13:00" } },
  { tokens: ["2h", "2hr", "2hrs", "2hour", "2hours", "2 h"], meaning: "Length in hours", suffix: "", expected: { durationMinutes: 120 } },
  { tokens: ["1.5h", "1h30m", "1h 30min", "1h30mins"], meaning: "Decimal hours or combined hours and minutes", suffix: "", expected: { durationMinutes: 90 } },
  { tokens: ["45m", "45min", "45mins", "45 m"], meaning: "Length in minutes", suffix: "", expected: { durationMinutes: 45 } },
  { tokens: ["#school", "#sch"], meaning: "Area name or ID prefix, case insensitive", suffix: "", expected: { areaId: "school" } },
  { tokens: ["#music"], meaning: "An existing area you named yourself (Music in this example)", suffix: "", expected: { areaId: "music" } },
  { tokens: ["#econ", "#ECON101"], meaning: "Project or course prefix; also selects its area", suffix: "", expected: { areaId: "school", projectId: "econ" } },
  { tokens: ["due fri", "due on friday", "due 2 oct"], meaning: "Deadline: a weekday, today, tomorrow, or a day and month", suffix: "", expected: { deadline: "2026-10-02" } },
  { tokens: ["daily", "every day"], meaning: "Repeat every day", suffix: "", expected: { repeat: { every: 1, unit: "day" } } },
  { tokens: ["every weekday", "weekdays"], meaning: "Repeat Monday to Friday", suffix: "", expected: { repeat: { every: 1, unit: "week", weekdays: [1, 2, 3, 4, 5] } } },
  { tokens: ["every 2 weeks", "every other week"], meaning: "Repeat every N days, weeks, months or years", suffix: "", expected: { repeat: { every: 2, unit: "week" } } },
  { tokens: ["every mon wed", "every monday and wednesday", "weekly on mon wed"], meaning: "Repeat on those weekdays; starts on the first of them", suffix: "", expected: { date: "2026-10-05", repeat: { every: 1, unit: "week", weekdays: [1, 3] } } },
  { tokens: ["every month on the 2nd tue", "monthly on the second tuesday"], meaning: "Monthly on the 1st to 4th or last weekday", suffix: "", expected: { date: "2026-10-13", repeat: { every: 1, unit: "month", monthDay: { kind: "weekday", nth: 2, weekday: 2 } } } },
  { tokens: ["every month on the last day", "monthly on the last day"], meaning: "Monthly on the last day; on the 15th works too", suffix: "", expected: { date: "2026-10-31", repeat: { every: 1, unit: "month", monthDay: { kind: "last_day" } } } },
  { tokens: ["daily after done", "daily after completion"], meaning: "Count the next date from when it was done", suffix: "", expected: { repeat: { every: 1, unit: "day", basis: "completion" } } },
  { tokens: ["daily until 18 dec", "daily until dec 18"], meaning: "Repeat until a date", suffix: "", expected: { repeat: { every: 1, unit: "day", ends: { kind: "on", date: "2026-12-18" } } } },
  { tokens: ["daily 10 times"], meaning: "Repeat a number of times", suffix: "", expected: { repeat: { every: 1, unit: "day", ends: { kind: "after", count: 10 } } } },
  { tokens: ["remind 30m before", "remind me 30 minutes before"], meaning: "Reminder before the start time (m, h or d)", suffix: " 17:00", expected: { time: "17:00", reminders: [{ type: "before", minutes: 30 }] } },
  { tokens: ["remind at 8am", "remind me at 08:00"], meaning: "Reminder at a time on the day", suffix: "", expected: { reminders: [{ type: "at_time", time: "08:00" }] } },
  { tokens: ["remind morning of", "remind me in the morning"], meaning: "Reminder at 09:00 on the day", suffix: "", expected: { reminders: [{ type: "morning_of" }] } },
  { tokens: ["remind day before", "remind me the day before"], meaning: "Reminder at 18:00 the evening before", suffix: "", expected: { reminders: [{ type: "day_before" }] } },
  { tokens: ["remind at start"], meaning: "Reminder at the start time", suffix: " 17:00", expected: { time: "17:00", reminders: [{ type: "at_start" }] } },
  { tokens: ["remind 2 days before due", "remind me 2d before the deadline at 6pm"], meaning: "Reminder before the deadline, at 18:00 unless a time is given", suffix: " due fri", expected: { deadline: "2026-10-02", reminders: [{ type: "deadline", daysBefore: 2, time: "18:00" }] } },
];
