/** Approved prototype tokens. The CSS is generated by `bun run tokens`. */
export const colors = {
  bg: "oklch(17% 0.006 70)",
  s1: "oklch(20.5% 0.007 70)",
  s2: "oklch(25% 0.008 70)",
  s3: "oklch(30% 0.009 70)",
  line: "oklch(30% 0.008 70)",
  ink: "oklch(96% 0.006 80)",
  "ink-2": "oklch(82% 0.008 80)",
  "ink-3": "oklch(69% 0.008 80)",
  on: "oklch(19% 0.02 70)",
  life: "oklch(80% 0.15 150)",
  biz: "oklch(79% 0.15 60)",
  school: "oklch(78% 0.11 245)",
  hot: "oklch(74% 0.17 28)",
  "area-red": "oklch(78% 0.15 28)",
  "area-yellow": "oklch(84% 0.14 95)",
  "area-purple": "oklch(78% 0.12 305)",
  "area-teal": "oklch(80% 0.12 185)",
  scrim: "oklch(10% 0.005 70 / 0.62)",
} as const;
export const areaColors = {
  school: colors.school,
  business: colors.biz,
  life: colors.life,
} as const;
export const namedAreaColors = {
  blue: colors.school, orange: colors.biz, green: colors.life,
  red: colors["area-red"], yellow: colors["area-yellow"],
  purple: colors["area-purple"], teal: colors["area-teal"], grey: colors["ink-2"],
} as const;
/** sRGB equivalents for the social-image renderer, which cannot use OKLCH. */
export const socialImageTokens = {
  background: "#121110", ink: "#f3f2ee", muted: "#a39f98", line: "#302d29",
  school: "#78c3fb", business: "#ffa844", hot: "#ff826c",
  wordmarkSize: 28, lineSize: 64, padding: 64, gap: 32,
} as const;
export const spacing = [4, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 36, 38, 40, 44, 46, 48, 60, 64, 72, 112, 120] as const;
export const radii = [8, 9, 10, 11, 12, 14, 16, 18, 38] as const;
export const typeSizes = [
  11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15, 15.5, 16, 17, 18, 19, 20, 21, 22, 24, 26, 30, 32, 36, 40, 44, 52, 64,
] as const;
export const controls = { compact: 32, primary: 36, touch: 44 } as const;
export const motion = {
  press: 160,
  transition: 200,
  panel: 250,
  easeOut: "cubic-bezier(0.23, 1, 0.32, 1)",
} as const;
export const layout = {
  hourHeight: 56, phoneHourHeight: 62, controlHeight: 44,
  landingChartHeight: 104,
  phonePadding: 18, phoneSheetPadding: 20, phoneSheetRadius: 24,
  phoneTimelineGutter: 46, phoneTabWidth: 64, phoneTabHeight: 50, phoneAddSize: 52,
} as const;
