/** Approved prototype tokens. The CSS is generated by `bun run tokens`. */
export const colors = {
  bg: "oklch(17% 0.006 70)",
  s1: "oklch(20.5% 0.007 70)",
  s2: "oklch(25% 0.008 70)",
  s3: "oklch(30% 0.009 70)",
  line: "oklch(30% 0.008 70)",
  ink: "oklch(96% 0.006 80)",
  "ink-2": "oklch(82% 0.008 80)",
  "ink-3": "oklch(69% 0.008 80)",
  on: "oklch(19% 0.02 70)",
  life: "oklch(80% 0.15 150)",
  biz: "oklch(79% 0.15 60)",
  school: "oklch(78% 0.11 245)",
  hot: "oklch(74% 0.17 28)",
  scrim: "oklch(10% 0.005 70 / 0.62)",
} as const;
export const areaColors = {
  school: colors.school,
  business: colors.biz,
  life: colors.life,
} as const;
/** sRGB equivalents for the social-image renderer, which cannot use OKLCH. */
export const socialImageTokens = {
  background: "#121110", ink: "#f3f2ee", wordmarkSize: 96, lineSize: 44,
  padding: 96, gap: 32,
} as const;
export const spacing = [4, 8, 12, 16, 24, 32, 48] as const;
export const radii = [8, 9, 10, 11, 12, 14, 16] as const;
export const typeSizes = [
  11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15, 16, 17, 18, 19, 22, 24, 30, 32, 40, 44, 64,
] as const;
export const motion = {
  press: 160,
  transition: 200,
  panel: 250,
  easeOut: "cubic-bezier(0.23, 1, 0.32, 1)",
} as const;
export const layout = { hourHeight: 56, controlHeight: 44 } as const;
