import { spawn } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import {redact} from '../skills/test-kriyan/scripts/lib/output.mjs';
const directory = new URL('../logs/21/', import.meta.url);
const [name, command, ...args] = process.argv.slice(2);
if (!name || !command || !/^[a-z0-9-]+$/.test(name)) throw new Error('Use <receipt-name> <command> [args].');
await mkdir(directory, {recursive:true});
const started = new Date().toISOString();
const child = spawn(command, args, {windowsHide:true, env:process.env});
let output = '';
const safeOutput = () => redact(output).replace(/(__clerk_db_jwt=)[^&\s]+/g,'$1[redacted]').replace(/("(?:clientId|client_id|accessToken|refreshToken|access_token|refresh_token)"\s*:\s*")[^"]+/g,'$1[redacted]');
const timer = setInterval(() => {void writeFile(new URL(`${name}.log`, directory), safeOutput());}, 3000);
child.stdout.on('data', chunk => { output += chunk; });
child.stderr.on('data', chunk => { output += chunk; });
child.on('error', error => { output += error.message; });
child.on('close', async code => {
 clearInterval(timer);
 await writeFile(new URL(`${name}.log`, directory), safeOutput());
 const receipt = {command:[command,...args],cwd:process.cwd(),started,finished:new Date().toISOString(),exit:code};
 await writeFile(new URL(`${name}.json`, directory), JSON.stringify(receipt,null,2));
 console.log(JSON.stringify(receipt)); process.exitCode = code ?? 1;
});
