import { test, expect } from "@playwright/test";
test("demo creates, edits, completes and resets without backend traffic", async ({ page }) => {
  const external: string[] = [];
  page.on("request", (request) => { if (/convex|clerk/.test(new URL(request.url()).hostname)) external.push(request.url()); });
  page.on("websocket", (socket) => { if (/convex|clerk/.test(new URL(socket.url()).hostname)) external.push(socket.url()); });
  await page.goto("/demo");
  await expect(page.getByText("This is a demo with sample data. Nothing is saved.")).toBeVisible();
  await page.getByRole("button", { name: "Add task", exact: true }).first().click();
  const dialog = page.getByRole("dialog", { name: "Add a task" });
  await dialog.getByRole("textbox").fill("demo proof today 11am #life");
  await dialog.getByRole("button", { name: "Add task", exact: true }).click();
  await expect(page.getByText("Demo proof", { exact: true })).toBeVisible();
  await page.getByRole("group", { name: "Demo proof, 11:00, no length", exact: true }).click();
  const details = page.getByRole("dialog", { name: "Task details" });
  await details.getByRole("button", { name: "30m", exact: true }).click();
  await expect(details.getByText("Runs from 11:00 to 11:30.")).toBeVisible();
  await details.getByRole("button", { name: "Close task details" }).click();
  await expect(details).not.toBeVisible();
  await page.getByRole("checkbox", { name: /Mark as done: Demo proof/ }).click();
  await expect(page.getByRole("checkbox", { name: /Mark as not done: Demo proof/ })).toBeChecked();
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await expect(page.getByRole("checkbox", { name: /Mark as done: Demo proof/ })).not.toBeChecked();
  await page.getByRole("button", { name: "List", exact: true }).click();
  await page.getByRole("button", { name: "Goals", exact: true }).click();
  await expect(page.getByRole("progressbar").first()).toBeVisible();
  await page.getByRole("button", { name: "Week", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Week", exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByText("Demo proof", { exact: true })).toHaveCount(0);
  expect(external).toEqual([]);
});
test("landing parser, iframe, keyboard tabs and copy are usable", async ({ page, context }) => {
  await context.grantPermissions(["clipboard-read", "clipboard-write"]);
  await page.goto("/");
  await expect(page.getByRole("heading", { level: 1 })).toHaveText("Your day on one timeline.");
  await expect(page.frameLocator("iframe").getByRole("button", { name: "Add task", exact: true }).first()).toBeVisible();
  await page.getByRole("button", { name: "essay fri #econ 2h", exact: true }).click();
  await expect(page.getByRole("status").first()).toContainText("School / Econ 101");
  await expect(page.getByRole("status").first()).toContainText("2h");
  const first = page.getByRole("tab", { name: "Claude", exact: true });
  await first.focus(); await page.keyboard.press("ArrowRight");
  await expect(page.getByRole("tab", { name: "Claude Code", exact: true })).toBeFocused();
  await expect(page.getByRole("tabpanel")).toContainText("claude mcp add");
  await page.getByRole("button", { name: "Copy setup" }).click();
  await expect(page.getByText("Setup copied.")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
test("docs, legal, metadata and planned download route respond", async ({ page, request }, info) => {
  await page.goto("/docs");
  await expect(page.getByRole("heading", { name: "Getting started", exact: true })).toBeVisible();
  if (info.project.name === "mobile") await page.getByText("Browse docs", { exact: true }).click();
  await page.getByRole("navigation", { name: "Documentation" }).getByRole("link", { name: "Quick add", exact: true }).click();
  await expect(page.getByRole("table").first()).toBeVisible();
  for (const route of ["/docs/mcp", "/docs/api", "/docs/cli", "/docs/android", "/docs/self-hosting", "/privacy", "/terms", "/sitemap.xml", "/robots.txt", "/opengraph-image"]) {
    const result = await request.get(route); expect(result.status(), route).toBe(200);
  }
  expect((await request.get("/docs/missing")).status()).toBe(404);
  const legacy = await request.get("/garden", { maxRedirects: 0 });
  expect(legacy.status()).toBe(307);
  expect(new URL(legacy.headers().location, "http://localhost:3004").pathname).toBe("/app");
  const release = await request.get("/download", { maxRedirects: 0 });
  expect(release.status()).toBe(307);
  expect(release.headers().location).toBe("https://github.com/kausthubh-coder/kriyan-garden/releases/latest");
  const headers = (await request.get("/demo")).headers();
  expect(headers["x-frame-options"]).toBe("SAMEORIGIN");
  expect(headers["content-security-policy"]).toContain("frame-ancestors 'self'");
  for (const route of ["/app", "/sign-in", "/sign-up", "/mcp", "/api/v1/tasks"]) {
    const redirect = await request.get(`${route}?proof=1`, { headers: { host: "kriyan.app" }, maxRedirects: 0 });
    expect(redirect.status()).toBe(307);
    expect(redirect.headers().location).toBe(`https://app.kriyan.app${route}?proof=1`);
  }
  expect((await request.get("/docs", { headers: { host: "www.kriyan.app" }, maxRedirects: 0 })).status()).toBe(200);
  const appRoot = await request.get("/", { headers: { host: "app.kriyan.app" }, maxRedirects: 0 });
  expect(appRoot.headers().location).toBe("https://app.kriyan.app/app");
});
test("desktop drag schedules, moves and resizes the shared Day task", async ({ page }, info) => {
  test.skip(info.project.name === "mobile", "Touch uses task details to set time and length; desktop uses pointer drag.");
  await page.goto("/demo");
  const tray = page.locator('[data-drag="place"]').filter({ hasText: "Call Amma" });
  const timeline = page.locator("[data-timeline]");
  await tray.waitFor();
  await page.locator("[data-day-scroll]").evaluate((el) => { el.scrollTop = 0; });
  const box = await timeline.boundingBox(), card = await tray.boundingBox();
  expect(box).not.toBeNull(); expect(card).not.toBeNull();
  if (!box || !card) return;
  await page.mouse.move(card.x + card.width / 2, card.y + 15); await page.mouse.down();
  await page.mouse.move(box.x + box.width / 2, box.y + 56 * 5, { steps: 15 }); await page.mouse.up();
  const moved = page.locator('[data-drag="move"]').filter({ hasText: "Call Amma" });
  await expect(moved).toBeVisible();
  const first = await moved.boundingBox();
  if (!first) throw new Error("Scheduled task missing");
  await page.mouse.move(first.x + first.width / 2, first.y + 12); await page.mouse.down();
  await page.mouse.move(first.x + first.width / 2, first.y + 68, { steps: 10 }); await page.mouse.up();
  await expect(moved).toHaveAttribute("aria-label", /13:00/);
  const edge = await moved.locator("[data-resize]").boundingBox();
  if (!edge) throw new Error("Resize target missing");
  await page.mouse.move(edge.x + edge.width / 2, edge.y + edge.height / 2); await page.mouse.down();
  await page.mouse.move(edge.x + edge.width / 2, box.y + 56 * 7, { steps: 10 }); await page.mouse.up();
  await expect(moved).toHaveAttribute("aria-label", /to 14:00/);
});
